server:
  port: 8081
mybatis:
  type-aliases-package: com.leyou.item.pojo
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hm49
    username: root
    password: 123456
  application:
    name: item-service #将来会作为微服务的名称

eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
    # register-with-eureka: true #服务提供方启动时，会监测该参数是否为true，true 注册给eureka
  instance:
    lease-renewal-interval-in-seconds: 5 #心跳时间，没5s给注册中心发一次
    lease-expiration-duration-in-seconds: 15 #过期时间







